### ISSUE TITLE
Missing Find Faulty Feature in Farm

### ISSUE THREAD

**Issue by bwatkins79** [achimismaili/featureadmin#1]
I just tried to use this and couldn't find the button "Find Faulty Feature in Farm"
Is this feature no longer there? Or is there another issue?

Thanks,
brian

**Comment by bwatkins79** [comment]
nevermind, im an idiot lol. thanks

**Comment by achimismaili** [comment]
Hey Brian, actually, you are right, at least in the version 2.4.8 for SP2013, the button is missing, but all faulty features are identified on load and shown in the feature definition table on the very right (maximize your window or scroll right). There might be an issue with removing faulty features in this version, so if you are looking for the button to find a faulty feature or if you are having issues to remove a faulty feature, use version 2.4.6.
As mentioned in the readme, we are working on a new version that fixes the problem with removing the faulty features...
