### ISSUE TITLE
No SharePoint 2016 support?

### ISSUE THREAD

**Issue by xantari** [achimismaili/featureadmin#2]
All documentation states this is only for up to SharePoint 2013. Is this true?

**Comment by AlexHowser** [comment]
yes, it seems like the 2013 edition isnt working on 2016

**Comment by achimismaili** [comment]
SharePoint 2016 support is coming soon, the new (at least beta) version 3 of feature admin is expected to be available in April 2018

**Comment by achimismaili** [comment]
Hello Xantari and Alex, the feature admin version 3 takes still some time, so I wanted to provide the old releases in a SP 2016 version. I now just verified, that both releases 2.4.6 (better for removing faulty features) and 2.4.8 are already working in SP 2016. 

You just have to run the exe as administrator (rightclick and select "Run as administrator").
